---
- name: Create raspberry-pi 4 multiservices server
  hosts: localhost

  roles:
    - role: system_config
      tags: system_config

    - role: jellyfin
      tags: jellyfin
    
    - role: qbittorrent
      tags: qbittorrent
    
    - role: pihole
      tags: pihole
    
    - role: nginx
      tags: nginx

  environment:
    mode: "test"
