---
- name: System update
  block:
    - name: Update list of the packages
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: "yes"
        state: latest

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ required_os_packages }}"

- name: Disk mounting
  vars:
    mode: "{{ ansible_env.mode }}"
  block:
    - name: Set disks variable based on environment
      set_fact:
        disks: "{{ prod_disks if mode == 'production' else test_disks }}"

    - name: Use losetup to disk mounting in test mode
      when: mode == "test"
      command: losetup {{ item.source }} {{ item.path }}
      loop: "{{ disks }}"
      ignore_errors: true

    - name: Create directories for mounting
      ansible.builtin.file:
        path: "{{ item.value }}"
        state: directory
        mode: "0755"
      loop: "{{ mountpoints | dict2items }}"

    - name: Get UUID of disk images
      command: blkid -s UUID -o value {{ item.path }}
      register: disk_uuids
      loop: "{{ disks }}"
      changed_when: false

    - name: Mount devices by UUID
      ansible.posix.mount:
        path: "{{ mountpoints[item.item.name] }}"
        src: "UUID={{ item.stdout }}"
        fstype: ntfs
        opts: defaults,permissions,uid=110,gid=114,umask=000
        state: present
      loop: "{{ disk_uuids.results }}"
