name: Build Docker Image

on:
  push:
    branches: ["master"]
    paths:
      - "Dockerfile"
      - "docker/**"
  pull_request:
    branches: ["master"]
    paths:
      - "Dockerfile"
      - "docker/**"
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set repository owner to lowercase
        id: set_lowercase
        run: |
          echo "repository_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --platform linux/arm64 -t ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest .
          docker push ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest
