name: Build Docker Image

on:
  push:
    branches: ["master"]
    paths:
      - "Dockerfile"
      - "docker/**"
  pull_request:
    branches: ["master"]
    paths:
      - "Dockerfile"
      - "docker/**"
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: "master"
  workflow_dispatch:

env:
  IMAGE_NAME: mockrpi-os
  IMAGE_TAG: latest


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set repository owner to lowercase
        id: set_lowercase
        run: |
          echo "repository_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/arm64
