name: Test Trigger

on:
  push:
    paths:
      - 'ansible/**'
  pull_request:
    paths:
      - 'ansible/**'

jobs:
  detect_changes:
    outputs:
      roles: ${{ steps.detect_changes.outputs.roles }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed files
        id: detect_changes
        run: |
          # For PR events, compare the base and head commits of the PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- ansible/*)
          else
            # For Push events, compare the before and after commits
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- ansible/*)

            # Check if 'before' commit exists (for force-push scenarios)
            if ! git cat-file commit ${{ github.event.before }} >/dev/null 2>&1; then
              echo "Force push detected! Fetching full history..."
              git fetch --unshallow  # Fetch the full history to check for differences
              CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- ansible/*)
            fi
          fi

          roles=$(echo $CHANGED_FILES | tr ' ' '\n' | awk -F'/' '{print $3}' | sort -u | tr '\n' ',' | sed 's/,$//')

          echo "roles=[\"$roles\"]" >> $GITHUB_OUTPUT
          echo "Changed files: $CHANGED_FILES"
          echo "Extracted roles: $roles"

  trigger_test:
    needs: detect_changes
    strategy:
      matrix:
        role: ${{ fromJson(needs.detect_changes.outputs.roles) }}
    uses: "./.github/workflows/test-runner.yaml"
    with:
      role: ${{ matrix.role }}
