name: Test Docker Image

on:
  push:
    branches: ["master"]
    paths:
      - "ansible/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  check_image:
    runs-on: ubuntu-latest
    outputs:
      image_exists: ${{ steps.check_image.outputs.image_exists }}
    steps:
      - uses: actions/checkout@v4

      - name: Set repository owner to lowercase
        id: set_lowercase
        run: |
          echo "repository_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check if Docker image exists
        id: check_image
        run: |
          if docker pull ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest; then
            echo "image_exists=true" >> $GITHUB_ENV
          else
            echo "image_exists=false" >> $GITHUB_ENV
          fi

  build_image:
    needs: check_image
    if: needs.check_image.outputs.image_exists == 'false'
    uses: ./.github/workflows/build.yaml

  run_tests:
    needs: [check_image, build_image]
    if: needs.check_image.outputs.image_exists == 'true' || needs.build_image.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Run Ansible tests
        run: |
          docker run --rm ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest ansible-playbook /ansible/playbooks/rpi_multi_services.yaml -i localhost