name: Test ansible playbook

on:
  push:
    branches: ["master"]
    paths:
      - "ansible/**"
  pull_request:
    branches: ["master"]
    paths:
      - "ansible/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repository owner to lowercase
        id: set_lowercase
        run: |
          echo "repository_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check if Docker image exists
        id: check_image
        run: |
          if docker pull ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest; then
            echo "Image exists."
            echo "::set-output name=image_exists::true"
          else
            echo "Image does not exist."
            echo "::set-output name=image_exists::false"
          fi

      - name: Build and push Docker image
        if: steps.check_image.outputs.image_exists == 'false'
        run: |
          docker build --platform linux/arm64 -t ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest .
          docker push ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest

      - name: Run Ansible tests
        if: steps.check_image.outputs.image_exists == 'true'
        run: |
          docker run --rm ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest ansible-playbook /ansible/your_playbook.yml -i localhost
