name: Test Docker Image

on:
  push:
    branches: ["master"]
    paths:
      - "ansible/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set repository owner to lowercase
        id: set_lowercase
        run: |
          echo "repository_owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check if Docker image exists
        id: check_image
        run: |
          if docker pull ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest; then
            echo "::set-output name=image_exists::true"
          else
            echo "::set-output name=image_exists::false"
          fi

  build_image:
    if: steps.check_image.outputs.image_exists == 'false'
    uses: ./.github/workflows/build.yaml
    with:
      ref: master

  run_tests:
    needs: build_image
    if: steps.check_image.outputs.image_exists == 'true' || needs.build_image.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Run Ansible tests
        run: |
          docker run --rm ghcr.io/${{ env.repository_owner }}/mockrpi-os:latest ansible-playbook /ansible/playbooks/rpi_multi_services.yaml -i localhost
