name: Test Ansible Role

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/test-runner.yaml"
  pull_request:
    branches: ["master"]
    paths:
      - ".github/workflows/test-runner.yaml"

  workflow_dispatch:
    inputs:
      role:
        description: "Role to test"
        required: false
        default: ""
        type: string

  workflow_call:
    inputs:
      role:
        description: "Role to test"
        required: false
        default: ""
        type: string

env:
  IMAGE_NAME: mockrpi-os
  IMAGE_TAG: latest

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
        repository_owner: ${{ steps.set_owner.outputs.owner }}
    steps:
      - name: Set repository owner to lowercase
        id: set_owner
        run: |
          owner="$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"
          variable="owner=$owner"
          echo "$variable" >> $GITHUB_ENV
          echo "$variable" >> $GITHUB_OUTPUT

  check:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      image_exists: ${{ steps.image_check.outputs.image_exists }}
    steps:
      - name: Check if Docker image exists
        id: image_check
        run: |
          repo_owner=${{ needs.setup.outputs.repository_owner }}
          ENCODED_TOKEN=$(echo -n "${{ secrets.GITHUB_TOKEN }}" | base64)
          REPO_LINK="https://ghcr.io/v2/$repo_owner/${{ env.IMAGE_NAME }}/tags/list"

          TAG_EXISTS=$(curl -s -H "Authorization: Bearer ${ENCODED_TOKEN}" \
              ${REPO_LINK} | \
              jq -r --arg TAG "${{ env.IMAGE_TAG }}" '.tags[] | select(. == $TAG)')

          echo "$TAG_EXISTS"

          if [[ -n "$TAG_EXISTS" ]]; then
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi

  build_image:
    needs: check
    if: ${{ needs.check.outputs.image_exists == 'false' }}
    uses: ./.github/workflows/build-image.yaml

  run_tests:
    needs: [setup, check]
    if: ${{ needs.check.outputs.image_exists == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Run Ansible tests
        run: |
          PLATFORM_ARCH="linux/arm64"
          IMAGE="${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          IMAGE_LINK="ghcr.io/${{ needs.setup.outputs.repository_owner }}/$IMAGE"
          PLAYBOOK_PATH="playbooks/rpi_multi_services.yaml"
          SPECIFIC_ROLE=""

          if [[ -n "${{ inputs.role }}" ]]; then
            SPECIFIC_ROLE="-t system_config -t ${{ inputs.role }}"
          fi

          docker run \
            --rm \
            --privileged \
            --platform $PLATFORM_ARCH \
            -v $(pwd)/ansible:/host_ansible \
            -e ANSIBLE_ROLES_PATH="/ansible/roles" \
            $IMAGE_LINK \
            ansible-playbook -vv $SPECIFIC_ROLE $PLAYBOOK_PATH -i localhost
